# Data

## Data sources

### Source 1:
New York neighborhood data from here
https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/labs/newyork_data.json

  Borough Neighborhood   Latitude  Longitude
0   Bronx    Wakefield  40.894705 -73.847201
1   Bronx   Co-op City  40.874294 -73.829939
2   Bronx  Eastchester  40.887556 -73.827806
3   Bronx    Fieldston  40.895437 -73.905643
4   Bronx    Riverdale  40.890834 -73.912585

### Source 2:
FourSquare API data with venues of all neighborhood data in New York

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Battery Park City,Coffee Shop,Park,Hotel,Clothing Store,Memorial Site,Gym,Boat or Ferry,Playground,Pizza Place,Cupcake Shop
1,Carnegie Hill,Coffee Shop,Café,Bar,Pizza Place,French Restaurant,Bookstore,Yoga Studio,Gym,Gym / Fitness Center,Wine Shop
2,Central Harlem,Seafood Restaurant,American Restaurant,Gym / Fitness Center,Chinese Restaurant,French Restaurant,African Restaurant,Bar,Cafeteria,Caribbean Restaurant,Event Space
3,Chelsea,Coffee Shop,Bakery,Art Gallery,American Restaurant,French Restaurant,Hotel,Wine Shop,Italian Restaurant,Market,Cycle Studio
4,Chinatown,Chinese Restaurant,Bakery,Cocktail Bar,American Restaurant,Optical Shop,Spa,Salon / Barbershop,Bar,Sandwich Place,Dim Sum Restaurant

## Explanation

Using the neightborhood data together with FourSquare API, I will cluster the neightborhoods and find out the best neighborhood for restuarants and offices.